exclude: "docs|node_modules|migrations|.git|.tox"
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: conda/meta.yaml

  # Can run individually with `pre-commit run black --all-files`
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Can run individually with `pre-commit run isort --all-files`
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # Can run individually with `pre-commit run flake8 --all-files`
  # Need to use flake8 GitHub mirror due to CentOS git issue with GitLab
  # https://github.com/pre-commit/pre-commit/issues/1206
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config=.flake8.cfg"]
        additional_dependencies: [flake8-isort==6.1.1]

  # Can run individually with `pre-commit run mypy --all-files`
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ["--config=pyproject.toml"]

# https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_schedule: monthly
