name: Bug Report
description: File a bug report to help us improve zppy
title: "[Bug]: "
labels: ["semver: bug"]
assignees: []
body:
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: |
              Thanks for reporting a bug! Please describe what you were trying to get done.
              Tell us what happened and what went wrong.
      validations:
          required: true

    - type: textarea
      id: machine
      attributes:
          label: What machine were you running on?
          description: |
	      List the machine(s) you encounter the issue on (e.g., Chrysalis, Compy, Perlmutter).
      validations:
          required: true

    - type: textarea
      id: zppy-version
      attributes:
          label: Environment
          description: |
              Paste your zppy version here (e.g., `zppy v2.3.0`).
      validations:
          required: true

    - type: textarea
      id: zppy-command
      attributes:
          label: What command did you run?
	  description: |
	      Copy the command causing the issue (e.g., `zppy -c tests/integration/generated/test_complete_run_chrysalis.cfg`). This will be automatically formatted into code, so no need for markdown backticks.
	  render: bash
      validations:
          required: true

    - type: textarea
      id: cfg-file
      attributes:
          label: Copy your cfg file
	  description: |
	      Copy the contents of your cfg file into the space below. This will be automatically formatted into code, so no need for markdown backticks.
	  render: bash
      validations:
          required: true

    - type: textarea
      id: status-output
      attributes:
          label: What jobs are failing?
	  description: |
	      Go to the `output` line of your cfg. `cd` into `post/scripts`. Copy the output of `grep -v "OK" *status`. This will be automatically formatted into code, so no need for markdown backticks.
	  render: bash
      validations:
          required: false

    - type: textarea
      id: stack-trace
      attributes:
          label: What stack trace are you encountering?
	  description: |
	      Copy a stack trace from one of your failing jobs. This will be automatically formatted into code, so no need for markdown backticks.
	  render: bash
      validations:
          required: false
