name: CI/CD Release Workflow

on:
  release:
    types: [published]

jobs:
  publish-to-anaconda:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Cache Conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-publish

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "zppy_publish"
          channel-priority: strict
          python-version: 3.7
          auto-update-conda: true
          # IMPORTANT: This needs to be set for caching to work properly!
          use-only-tar-bz2: true

      - name: Additional Conda Config
        run: |
          conda install anaconda-client conda-build conda-verify
          conda config --set anaconda_upload no

      - name: Build Conda Package
        run: conda build -c conda-forge --output-folder . .

      - name: Publish to Anaconda (e3sm channel)
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          label="main"

          for file in noarch/*.tar.bz2; do
            if [[ "$file" == noarch/*"rc"*.tar.bz2 ]]; then
               label="e3sm_dev"
            fi
          done

          echo Uploading to conda-forge with \'$label\' label
          anaconda upload --label $label noarch/*.tar.bz2 --force
